version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: videoknowledge
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  flask_app:
    build:
      context: ./backend
    container_name: flask_app
    environment:
      - FLASK_APP=app.py
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db

  streamlit_app:
    build:
      context: ./frontend
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask_app

volumes:
  pgdata:
